"""add_verifications

Revision ID: 1c0640e3ceda
Revises: 1bef516cb306
Create Date: 2025-12-10 23:19:22.091229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c0640e3ceda'
down_revision: Union[str, None] = '1bef516cb306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Pre-fill NULLs with default values before setting NOT NULL
    op.execute("UPDATE tasks SET metadata = '{}'::jsonb WHERE metadata IS NULL")
    op.execute("UPDATE artifacts SET metadata = '{}'::jsonb WHERE metadata IS NULL")
    op.execute("UPDATE consensus SET agreed_items = '[]'::jsonb WHERE agreed_items IS NULL")
    op.execute("UPDATE findings SET metadata = '{}'::jsonb WHERE metadata IS NULL")
    op.execute("UPDATE patterns SET examples = '[]'::jsonb WHERE examples IS NULL")
    op.execute("UPDATE reviews SET issues = '[]'::jsonb WHERE issues IS NULL")
    op.execute("UPDATE verifications SET plan_deviations = '[]'::jsonb WHERE plan_deviations IS NULL")
    op.execute("UPDATE verifications SET issues = '[]'::jsonb WHERE issues IS NULL")

    op.alter_column('analyses', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('analyses', 'round_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('analyses', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('analyses', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_analyses_agent'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_task'), table_name='analyses')
    op.alter_column('artifacts', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('artifacts', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_artifacts_task'), table_name='artifacts')
    op.alter_column('consensus', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('consensus', 'agreed_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('consensus', 'human_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('consensus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_consensus_task'), table_name='consensus')
    op.alter_column('conversations', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_conversations_task'), table_name='conversations')
    op.alter_column('decisions', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_decisions_task'), table_name='decisions')
    op.alter_column('disagreements', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('disagreements', 'consensus_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('disagreements', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('disagreements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_disagreements_task'), table_name='disagreements')
    op.alter_column('execution_log', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('execution_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_execution_log_phase'), table_name='execution_log')
    op.drop_index(op.f('idx_execution_log_task'), table_name='execution_log')
    op.alter_column('explorations', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('explorations', 'agent',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'gemini'::character varying"))
    op.alter_column('explorations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_explorations_task'), table_name='explorations')
    op.alter_column('file_snapshots', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('file_snapshots', 'snapshot_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('findings', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('findings', 'round_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('findings', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('findings', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_findings_agent'), table_name='findings')
    op.drop_index(op.f('idx_findings_severity'), table_name='findings')
    op.drop_index(op.f('idx_findings_task'), table_name='findings')
    op.alter_column('guardrails', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('human_interventions', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('human_interventions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('human_interventions', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('impl_tasks', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('impl_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('impl_tasks', 'codex_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('impl_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_impl_tasks_status'), table_name='impl_tasks')
    op.drop_index(op.f('idx_impl_tasks_task'), table_name='impl_tasks')
    op.alter_column('memories', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('memories', 'times_referenced',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('memories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_memories_category'), table_name='memories')
    op.alter_column('patterns', 'examples',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('patterns', 'times_applied',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('patterns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patterns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_patterns_type'), table_name='patterns')
    op.alter_column('preferences', 'set_by',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'human'::character varying"))
    op.alter_column('preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('questions', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('questions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_questions_status'), table_name='questions')
    op.drop_index(op.f('idx_questions_task'), table_name='questions')
    op.alter_column('reviews', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reviews', 'issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rounds', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('rounds', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'in_progress'::character varying"))
    op.alter_column('rounds', 'gemini_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('rounds', 'claude_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('rounds', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_rounds_task'), table_name='rounds')
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'scoping'::character varying"))
    op.alter_column('tasks', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'max_rounds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('tasks', 'skip_debate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_tasks_slug'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.alter_column('verifications', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('verifications', 'tests_ran',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('verifications', 'lint_ran',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('verifications', 'build_ran',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('verifications', 'plan_deviations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('verifications', 'issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('verifications', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_verifications_task'), table_name='verifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_verifications_task'), 'verifications', ['task_id'], unique=False)
    op.alter_column('verifications', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('verifications', 'issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('verifications', 'plan_deviations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('verifications', 'build_ran',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('verifications', 'lint_ran',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('verifications', 'tests_ran',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('verifications', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_slug'), 'tasks', ['slug'], unique=False)
    op.alter_column('tasks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'skip_debate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'max_rounds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('tasks', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'scoping'::character varying"))
    op.create_index(op.f('idx_rounds_task'), 'rounds', ['task_id'], unique=False)
    op.alter_column('rounds', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rounds', 'claude_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('rounds', 'gemini_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('rounds', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'in_progress'::character varying"))
    op.alter_column('rounds', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('reviews', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_questions_task'), 'questions', ['task_id'], unique=False)
    op.create_index(op.f('idx_questions_status'), 'questions', ['status'], unique=False)
    op.alter_column('questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('questions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('questions', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('preferences', 'set_by',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'human'::character varying"))
    op.create_index(op.f('idx_patterns_type'), 'patterns', ['pattern_type'], unique=False)
    op.alter_column('patterns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patterns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patterns', 'times_applied',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('patterns', 'examples',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_memories_category'), 'memories', ['category'], unique=False)
    op.alter_column('memories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('memories', 'times_referenced',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('memories', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.create_index(op.f('idx_impl_tasks_task'), 'impl_tasks', ['task_id'], unique=False)
    op.create_index(op.f('idx_impl_tasks_status'), 'impl_tasks', ['status'], unique=False)
    op.alter_column('impl_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('impl_tasks', 'codex_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('impl_tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('impl_tasks', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('human_interventions', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('human_interventions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('human_interventions', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('guardrails', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_findings_task'), 'findings', ['task_id'], unique=False)
    op.create_index(op.f('idx_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('idx_findings_agent'), 'findings', ['agent'], unique=False)
    op.alter_column('findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('findings', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('findings', 'analysis_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('findings', 'round_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('findings', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('file_snapshots', 'snapshot_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_snapshots', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_explorations_task'), 'explorations', ['task_id'], unique=False)
    op.alter_column('explorations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('explorations', 'agent',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'gemini'::character varying"))
    op.alter_column('explorations', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_execution_log_task'), 'execution_log', ['task_id'], unique=False)
    op.create_index(op.f('idx_execution_log_phase'), 'execution_log', ['phase'], unique=False)
    op.alter_column('execution_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_log', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_disagreements_task'), 'disagreements', ['task_id'], unique=False)
    op.alter_column('disagreements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('disagreements', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('disagreements', 'consensus_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('disagreements', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_decisions_task'), 'decisions', ['task_id'], unique=False)
    op.alter_column('decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('decisions', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_conversations_task'), 'conversations', ['task_id'], unique=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_consensus_task'), 'consensus', ['task_id'], unique=False)
    op.alter_column('consensus', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('consensus', 'human_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('consensus', 'agreed_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('consensus', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_artifacts_task'), 'artifacts', ['task_id'], unique=False)
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifacts', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('artifacts', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_analyses_task'), 'analyses', ['task_id'], unique=False)
    op.create_index(op.f('idx_analyses_agent'), 'analyses', ['agent'], unique=False)
    op.alter_column('analyses', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyses', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('analyses', 'round_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('analyses', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
